version: 0.2

phases:
  pre_build:
    commands:
      - echo "Preparing the build environment..."
      - chmod +x ./gradlew
      - ./gradlew clean build
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=public.ecr.aws/q4r7n5w9/account/repo
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 058264489222.dkr.ecr.us-east-1.amazonaws.com
      -
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  build:
    commands:
      - echo "Build started on $(date)"
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - DOCKER_CONTAINER_NAME=newrepo/boa
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo Printing imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - build/libs/accounts.jar
